| **Question**                                                                                                                                            | **Answer**                                                                                                                                                                                                                         |
|--------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| What was discussed in the previous session?                                                                                                            | Risk management and cybersecurity as a risk to be addressed for appropriate solutions.                                                                                                       |
| Who did students have a session with last week?                                                                                                        | Mr. Sai, who shared insights from practical experience in handling cybersecurity issues.                                                                                                     |
| What is today's topic in the Cybersecurity and Privacy course?                                                                                         | An overview of cybersecurity technologies, particularly focusing on the protection role of technology.                                                                                       |
| How does risk management identify assets?                                                                                                              | By identifying assets as potential targets or the focus of enemy attacks.                                                                                                                    |
| What are the three stages in risk management?                                                                                                          | 1) Identify assets and threats, 2) Assessment (measuring the value and impact of assets), and 3) Calculate risk.                                                                            |
| How is risk assessment performed quantitatively?                                                                                                       | By valuing assets and using threat intelligence to estimate the probability and success rate of threats.                                                                                     |
| What are the two important measures in assessing risk?                                                                                                 | Loss frequency and loss magnitude.                                                                                                                                                          |
| What does loss frequency represent?                                                                                                                    | The probability of an attack multiplied by the probability of the attack being successful.                                                                                                  |
| What is loss magnitude?                                                                                                                                | Asset value multiplied by the percentage of exposure.                                                                                                                                       |
| How is residual risk calculated?                                                                                                                       | Residual risk is calculated as the product of loss frequency and loss magnitude minus protection measures plus a measurement uncertainty.                                                    |
| What worksheet is used in risk assessment to assess vulnerability?                                                                                     | The TVA (Threat Vulnerability Asset) worksheet.                                                                                                                                             |
| What decision must management make after assessing risk for each asset?                                                                                | Management decides on actions to manage the identified risks for each asset, such as defense, transfer, mitigation, acceptance, or termination.                                             |
| What are the five options for risk management?                                                                                                         | 1) Defense, 2) Transfer, 3) Mitigation, 4) Acceptance, and 5) Termination.                                                                                                                  |
| Why is defense not the only option in cybersecurity risk management?                                                                                   | Management literature includes other options like transfer, mitigation, acceptance, and termination, each providing different ways to handle risk.                                          |
| What does the defense option in risk management involve?                                                                                               | Investing in cybersecurity technologies and personnel to reduce exposure and the chance of successful attacks.                                                                               |
| What is an example of the transferal option in risk management?                                                                                        | Non-IT companies may choose to outsource cybersecurity responsibilities to reduce their own risk exposure.                                                                                   |




| **Question** | **Answer** |
|--------------|------------|
| What topic was covered in the previous session? | Risk management, particularly addressing cybersecurity as a risk. |
| Who conducted a session with students last week? | Mr. Sai conducted the session. |
| What is today’s focus in the Cybersecurity and Privacy course? | An overview of cybersecurity technologies, specifically those used for protection. |
| What is the main role of cybersecurity technologies discussed today? | The protection role, especially from a defense perspective. |
| What is the first step in risk management? | Identifying assets and potential threats. |
| What is the second stage of risk management? | Assessment, which includes measuring asset values and evaluating threats quantitatively. |
| What two key measures are used to assess risk? | Loss frequency and loss magnitude. |
| How is loss frequency calculated? | As the product of the probability of an attack and the probability of a successful attack. |
| How is loss magnitude defined? | As the exposure of an asset, calculated by asset value multiplied by the percentage exposed. |
| What is residual risk? | The remaining risk after implementing protection mechanisms, factoring in measurement uncertainty. |
| What does the term "TVA worksheet" refer to? | A worksheet that maps threats, vulnerabilities, and assets to assess risk. |
| Who ultimately makes decisions on risk management in an organization? | The management, based on quantitative risk assessments. |
| What are the five options for risk management? | Defense, transfer, mitigation, acceptance, and termination. |
| What does the "defense" option entail? | Investing in safeguards like cybersecurity technologies to reduce the chance of successful attacks. |
| What is risk transferal in cybersecurity? | Shifting the risk to a third party, such as outsourcing IT management to a vendor. |
| How does cloud computing relate to risk transfer? | It involves transferring data management to a third-party vendor, which assumes responsibility for cybersecurity. |
| What is "managed services" in IT? | A model where a service provider manages IT assets while the client retains ownership. |
| Give an example of a risk transfer scenario. | TCS managing IT services for a client, assuming cybersecurity responsibilities. |
| How does mitigation differ from defense? | Mitigation aims to reduce the impact of an attack after it occurs, while defense prevents the attack. |
| What is an example of a mitigation strategy? | Investing in contingency planning or a hot site to minimize damage if an attack happens. |
| What does "acceptance" mean in risk management? | Choosing to accept a certain level of risk without implementing additional defense or mitigation measures. |
| Why might an organization choose the acceptance strategy? | Due to the low criticality of data or minimal financial impact of a potential cyber attack. |
| What is termination in risk management? | Eliminating or selling off a business unit or IT asset due to the high cost of maintaining cybersecurity. |


| **Question**                                                                                                   | **Answer**                                                                                                                                                                                                                     |
|---------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| What is the primary purpose of outsourcing IT asset management?                                               | To transfer risk from the owner of the asset to a third party, usually a service provider.                                                                                                                                    |
| What is a Service Level Agreement (SLA)?                                                                      | An agreement that specifies the expected level of service, such as system availability at 99.99%, which the service provider is responsible for maintaining.                                                                  |
| How does cloud computing relate to risk transfer?                                                             | Cloud computing involves transferring data management to a third-party vendor, which assumes responsibility for data security and risk management.                                                                             |
| What are managed services in IT?                                                                              | Managed services involve a third-party provider managing IT services, where the client retains ownership of assets, but the provider ensures system availability and cybersecurity.                                           |
| What is an example of a risk transfer failure?                                                                | The iPremier case, where the third-party provider was unprofessional and lacked cybersecurity capabilities, highlighting the importance of choosing competent providers.                                                       |
| What is the difference between defense and mitigation in risk management?                                      | Defense involves preventing attacks (e.g., firewalls), while mitigation reduces the impact after an attack occurs (e.g., contingency planning).                                                                               |
| What does mitigation focus on?                                                                                | Minimizing the impact of a cybersecurity incident after it has already occurred.                                                                                                                                               |
| What is an example of a mitigation strategy?                                                                  | Investing in contingency planning and creating a team or resources for incident response to reduce the impact of attacks.                                                                                                     |
| What is risk acceptance in cybersecurity?                                                                     | Choosing to accept the risk without investing in defense or mitigation, often based on cost-benefit analysis and the criticality of data or applications.                                                                     |
| Under what conditions might an organization choose risk acceptance?                                           | When the potential loss is low compared to the cost of investing in cybersecurity measures.                                                                                                                                    |
| What is risk termination?                                                                                     | Terminating a business activity or asset when cybersecurity costs outweigh the potential benefits, making it uneconomical to continue.                                                                                        |
| What is economic justification in risk management?                                                            | Assessing whether the benefits of cybersecurity investments (like defense or mitigation) outweigh the costs through cost-benefit analysis.                                                                                    |
| What is the purpose of Annualized Loss Expectancy (ALE)?                                                      | To estimate the expected loss over a year by considering asset value and exposure frequency, helping to justify risk management investments.                                                                                   |
| What is Single Loss Expectancy (SLE)?                                                                         | The expected loss from a single incident, calculated as the asset value multiplied by the exposure factor.                                                                                                                    |
| What does the term ALE prior refer to?                                                                        | The estimated annualized loss before implementing any cybersecurity controls.                                                                                                           |
| What is ALE post?                                                                                             | The estimated annualized loss after implementing cybersecurity controls, expected to be lower due to improved protections.                                                                                                    |
| What does ACS stand for in risk management?                                                                   | Annualized Cost of Safeguard, which is the yearly cost of implementing a specific cybersecurity control.                                                                                                                      |
| What justifies the investment in a cybersecurity control?                                                     | If the combined ALE post and ACS are less than the ALE prior, indicating that the control leads to positive cash flow or gain.                                                                                                |
| What is the purpose of monitoring in risk management?                                                         | To ensure that cybersecurity investments are providing the anticipated benefits, as actual outcomes may differ from initial estimates.                                                                                        |
| Why is cost-benefit analysis essential in cybersecurity decision-making?                                      | It helps ensure that investments in cybersecurity controls are economically justified by showing a net positive impact on the organization’s finances.                                                                        |
