| Question                                                                                     | Answer                                                                                                                                                                                |
|----------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| What is the importance of identifying and assessing threats in cybersecurity?                | Identifying and assessing threats is crucial for protecting assets and understanding the risks associated with various cyber threats.                                               |
| How many cyber threats exist today?                                                          | There are many cyber threats today, potentially numbering in the hundreds, and it's essential to understand the current landscape of threats.                                       |
| What is threat intelligence?                                                                  | Threat intelligence is informed information about current cyber threats, including their criticality, likelihood, frequency, and potential impact.                                   |
| Where can one find threat intelligence?                                                      | Threat intelligence is often available through professional bodies, subscriptions to threat intelligence services, and networking with cybersecurity organizations.                   |
| How are cyber threats classified?                                                             | Cyber threats can be classified into categories, such as human error, intellectual property compromises, espionage, information extortion, and technological obsolescence.          |
| What is espionage in the context of cybersecurity?                                          | Espionage refers to acts by individuals, often insiders, who betray their organization or country by leaking sensitive information.                                                  |
| What is technological obsolescence and why is it a threat?                                   | Technological obsolescence occurs when systems are outdated (e.g., using Windows 8) and not updated, increasing vulnerability to cyber threats.                                      |
| How can threats be ranked in terms of severity?                                             | Threats can be ranked by calculating a weighted score based on the frequency of occurrence and their potential impact, using data collected for this purpose.                        |
| What distinguishes asset valuation from threat intelligence?                                 | Asset valuation can be conducted internally by organizations through surveys, while threat intelligence relies on external data from specialized bodies.                              |
| What is the relationship between threats and assets in cybersecurity management?             | Cybersecurity management involves assessing threats against assets, resulting in a threat-asset combination that guides protective measures and strategies.                           |


| **Question**                                                                                                                                                             | **Answer**                                                                                                                                                                          |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| What is the focus of the discussion regarding threats?                                                                                                                 | The identification and assessment of cyber threats is crucial for protecting assets.                                                                                             |
| How many cyber threats exist today?                                                                                                                                   | There are many, with hundreds identified.                                                                                                                                         |
| What is threat intelligence?                                                                                                                                           | Threat intelligence is informed information about current cyber threats, including their criticality, likelihood, and impact.                                                    |
| Where can one find threat intelligence?                                                                                                                                 | Threat intelligence can be obtained from professional bodies and cybersecurity managers, often through subscriptions or networks.                                                 |
| What are the categories of threats mentioned?                                                                                                                         | Threats can be categorized into acts of human error, compromises to intellectual property, espionage, information extortion, and technological obsolescence.                     |
| What is espionage?                                                                                                                                                     | Espionage is the act of leaking information by someone within an organization, betraying it for personal gain or the benefit of another entity.                                   |
| How is technological obsolescence considered a threat?                                                                                                                | Using outdated technology can make systems vulnerable to cyber threats, such as operating on an unsupported version of software.                                                  |
| What is vulnerability assessment?                                                                                                                                      | Vulnerability assessment evaluates how protected an asset is from various threats, identifying any remaining vulnerabilities.                                                     |
| What is the purpose of a Threat Vulnerability Asset (TVA) worksheet?                                                                                                  | The TVA worksheet is used to assess vulnerabilities associated with each asset in relation to various threats, facilitating a comprehensive risk assessment.                      |
| What are the two key terms used in risk assessment?                                                                                                                   | Loss frequency and loss magnitude are the key terms used to calculate risk.                                                                                                      |
| What does loss frequency refer to?                                                                                                                                     | Loss frequency assesses the likelihood of an attack occurring and the expected probability of its success.                                                                         |
| How is loss magnitude defined?                                                                                                                                         | Loss magnitude, sometimes referred to as asset exposure, combines the value of an information asset with the percentage of that asset lost in a successful attack.                  |
| What is the formula for calculating residual risk?                                                                                                                    | Residual risk = (Loss frequency × Loss magnitude) - (Percentage of risk mitigated by current controls) + Measurement uncertainty.                                               |
| What does a high loss magnitude indicate?                                                                                                                               | A high loss magnitude indicates that a large percentage of the asset would be affected in the event of a successful attack, leading to significant financial loss.                  |
| Why is it essential to assess vulnerabilities quantitatively?                                                                                                          | Quantitative assessment allows organizations to utilize data to better understand risk levels, making it easier to prioritize resources and mitigation strategies effectively.      |


| **Question**                                                                                                                                                       | **Answer**                                                                                                                                                                                                                                                                                    |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| What is vulnerability assessment in the context of risk assessment?                                                                                             | Vulnerability assessment evaluates each combination of assets and threats to identify potential vulnerabilities. It assesses whether an asset is protected from various threats and determines if any vulnerabilities remain.                                                                   |
| What does a TVA worksheet represent?                                                                                                                            | A TVA (Threat Vulnerability Asset) worksheet is a tool used in risk assessment that charts vulnerabilities for different threats against specific assets. It helps in understanding the vulnerabilities present in an organization by allowing ranking of assets and threats based on criticality. |
| What are the two terms used to calculate risk?                                                                                                                 | The two terms used to calculate risk are loss frequency and loss magnitude.                                                                                                                                                                                                                  |
| What is loss frequency?                                                                                                                                         | Loss frequency assesses the likelihood of an attack combined with the expected probability of its success. It combines two probabilities: how likely an attack can happen and the chance of success if that attack occurs.                                                                       |
| What is loss magnitude?                                                                                                                                        | Loss magnitude, sometimes referred to as asset exposure, combines the value of an information asset with the percentage of that asset lost in the event of a successful attack. It is calculated as the asset value multiplied by the percentage of the asset that would be affected during an attack. |
| How is residual risk calculated?                                                                                                                                 | Residual risk is calculated using the formula: (Loss frequency * Loss magnitude) - Current controls + Measurement uncertainty. It considers the potential impact of risks after accounting for existing controls and the uncertainty of measurements.                                            |
| What does measurement uncertainty refer to?                                                                                                                    | Measurement uncertainty refers to the potential errors in assessing loss frequency and loss magnitude, indicating that these are often subjective estimates rather than objective assessments.                                                                                                  |
| What example scenario is provided for calculating residual risk?                                                                                               | An example scenario involves an e-commerce database with a 10% chance of an attack this year, a 50% chance of success if attacked, an asset valued at 50, and 80% of the asset being compromised in a successful attack. These values are used to calculate residual risk using the provided formula. |
| Why is it challenging to obtain accurate quantitative estimates for risk assessment?                                                                           | Obtaining accurate quantitative estimates is challenging due to the subjective nature of many assessments, leading to reliance on qualitative evaluations. Practitioners often find it difficult to objectively assess values and calculate risk quantitatively.                                         |
| What is the next step in risk management after obtaining vulnerability values?                                                                                   | The next step involves determining what actions the organization should take in terms of controls and monitoring to manage the identified risks effectively.                                                                                                                                   |
